- name: "Install SIP3 Twig for CentOS-family"
  include: centos.yml
  when:
    - ansible_facts['distribution'] | lower in ["centos", "sangoma", "oracle"]

- name: "Install SIP3 Twig for Debian/Ubuntu"
  include: debian.yml
  when:
    (ansible_facts['distribution'] | lower == "debian" and
      ansible_facts['distribution_major_version'] | int >= 10) or
    (ansible_facts['distribution'] | lower == "ubuntu" and
      ansible_facts['distribution_version'] in ["20.04"])

- name: "Configure SIP3 Twig"
  include: configure.yml
