- name: "Installing"
  block:
    - name: "Add repositories"
      block:
        - name: "Install gnupg packages"
          apt:
            pkg:
              - gnupg
            update_cache: yes

        - name: "Add signing key for NGINX repository"
          apt_key:
            url: "https://nginx.org/keys/nginx_signing.key"
            state: present

        - name: "Add NGINX repository"
          apt_repository:
            repo: deb http://nginx.org/packages/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['lsb']['codename'] }} nginx
            state: present
            filename: nginx

    - name: "Check and install tar, unzip and NGINX"
      apt:
        pkg:
          - tar
          - unzip
          - nginx
        update_cache: yes
      notify:
        - restart nginx
  when: state == "started"

- name: "Uninstalling"
  block:
    - name: "Stop NGINX"
      systemd:
        name: nginx
        enabled: no
        state: stopped

    - name: "Uninstall NGINX"
      apt:
        pkg:
          - nginx
        state: absent

    - name: "Purge project files"
      block:
        - name: "Checking project files"
          stat:
            path: "{{item}}"
          register: folder_stats
          with_items:
            - "/var/www/sip3-hoof"
        - name: "Delete project files"
          file:
            path: "{{ item.item }}"
            force: true
            state: absent
          when: item.stat.exists == true and item.stat.isdir == false
          with_items:
            - "{{folder_stats.results}}"
        - name: "Delete project folders"
          file:
            path: "{{ item.item }}"
            force: true
            state: absent
          when: item.stat.exists == true and item.stat.isdir == true
          with_items:
            - "{{folder_stats.results}}"
      ignore_errors: yes
  when: state == "absent"
